### ISSUE TITLE
[Bug] panic: runtime error  in VmwareSource

### ISSUE THREAD

**Issue by broerman** [SRC-doo/netbox-ssot#481]
### Is this urgent?

No

### How are you running netbox-ssot?

Docker

### What is the version of netbox-ssot

v1.8.0

### Which module has the issue?

VMware

### Share your configuration

```yaml
netbox:
...
  removeOrphans: False
  removeOrphansAfterDays: 3

source:
  - name: vsphere
    type: vmware
...
    permittedSubnets:
      - "10.0.0.0/8"
      - "172.16.0.0/12"

    clusterSiteRelations:
      - .*amsap.* = AMSAP
...

    hostSiteRelations:
      - .*amsap.* = AMSAP
...

    vlanGroupRelations:
      - .*AMSAP.* = AMSAP
 ...
```

### What is the problem?

Since netbox-ssot:v1.8.0 sync process stops with 
panic: runtime error: invalid memory address or nil pointer dereference
This also happens with v1.9.14

v1.7.13 runs with no problem

### Steps to reproduce

docker run -v /usr/local/etc/netbox/netbox-ssot-prod.yaml:/app/config.yaml bl4ko/netbox-ssot:v1.8.0

### What did you expect to happen?

sync complets

### What actually happened?

sync crashes

### Share DEBUG-level logs (remove sensitive information)

```plaintext
2025/02/14 13:06:59 INFO    (vsphere): Syncing source...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x710d79]

goroutine 33 [running]:
github.com/bl4ko/netbox-ssot/internal/netbox/inventory.(*NetboxInventory).AddVlan(0xc0005c2e00, {0x1424e48, 0xc001886900}, 0xc005737300)
        github.com/bl4ko/netbox-ssot/internal/netbox/inventory/add_items.go:695 +0x259
github.com/bl4ko/netbox-ssot/internal/source/vmware.(*VmwareSource).syncNetworks(0xc00176fa40, 0xc0005c2e00)
        github.com/bl4ko/netbox-ssot/internal/source/vmware/vmware_sync.go:52 +0x328
github.com/bl4ko/netbox-ssot/internal/source/vmware.(*VmwareSource).Sync(0xc00176fa40, 0xc0005c2e00)
        github.com/bl4ko/netbox-ssot/internal/source/vmware/vmware.go:195 +0x307
main.main.func1({0x1424e48, 0xc001886900}, {0x1422650, 0xc00176fa40})
        ./main.go:114 +0x2cd
created by main.main in goroutine 1
        ./main.go:94 +0x75c
```
