### ISSUE TITLE
Failed to sync Cisco 3850 switch with enabled netconf

### ISSUE THREAD

**Issue by pnmrmax** [SRC-doo/netbox-ssot#498]
### Is this urgent?

No

### How are you running netbox-ssot?

Docker

### Which version of netbox are you using

4.2.3

### Which version of netbox-ssot are you running

Running version v1.9.7 built on 2025-02-05T05:27:38Z (commit 6c9869d3b9b3f478063893e1657a66972622900f)

### Which module has the issue?

IOS-XE

### Share your configuration

```yaml
netbox:
  apiToken: "XXXX"
  hostname: "10.XX.XX.XX"
  httpScheme: https
  port: 443
  timeout: 30
  sourcePriority: ["cs3850"] # Not required, but recommended

source:
  - name: cs3850
    type: ios-xe
    hostname: 10.XX.XX.XX
    username: XXXXX
    password: XXXXXXXXXXXXXXXXXXX
    port: 830
    validateCert: False
    hostTenantRelations:
      - .* = MyTenant
    hostSiteRelations:
      - .* = MySite
    vlanTenantRelations:
      - .* = MyTenant
    collectArpData:
      true
```

### What is the problem?

ERROR   (cs3850): failed to open driver: errConnectionError: encountered error output during in channel ssh authentication, error: 'no matching host key found for host, their offer: Their offer: ssh-rsa'

2025/02/21 08:45:11 INFO    (main): Skipping removing orphaned objects because run failed...
2025/02/21 08:45:11 INFO    (main): ⚠ syncing of source cs3850 failed

### Steps to reproduce

1. sudo docker run -v /opt/netbox/config-netbox-autodiscovery.yaml:/app/config.yaml ghcr.io/bl4ko/netbox-ssot

### What did you expect to happen?

Sync cisco with netconf

All other sources works perfectly such as vcenter,proxmox-cluster,fortigates

### What actually happened?

2025/02/21 08:57:18 ERROR   (cs3850): failed to open driver: errConnectionError: encountered error output during in channel ssh authentication, error: 'no matching host key found for host, their offer: Their offer: ssh-rsa'
2025/02/21 08:57:24 INFO    (main): Skipping removing orphaned objects because run failed...
2025/02/21 08:57:24 INFO    (main): ⚠ syncing of source cs3850 failed

### Share DEBUG-level logs (remove sensitive information)

```plaintext

```

### Share your environment details

Ubuntu 22.04, Docker version 27.5.1, build 9f9e405
