### ISSUE TITLE
[Bug] SSOT stack-trace when running for a Proxmox cluster

### ISSUE THREAD

**Issue by AskskwBv8T2nrm4Qnj** [SRC-doo/netbox-ssot#507]
### Is this urgent?

No

### How are you running netbox-ssot?

Docker

### Which version of netbox are you using

v4.2.4

### Which version of netbox-ssot are you running

Running version v1.10.4 built on 2025-02-26T14:32:48Z (commit 69f088e94336316effe297496bfbba00090d7575)

### Which module has the issue?

Proxmox

### Share your configuration

```yaml
logger:
  level: 0
  dest: ""

netbox:
  apiToken: "blablabla"
  hostname: "netbox.example.com"
  httpScheme: https
  port: 443
  timeout: 30
  sourcePriority: ["proxcluster"]

source:
  - name: proxcluster
    type: proxmox
    username: netboxuser@pve
    password: "mypassword"
    httpScheme: https
    hostname: proxmox.example.com
    validateCert: true
    interfaceFilter: veth*
    ignoredSubnets: ["127.0.0.0/8", "169.254.0.0/16", "::1/128","fe80::/16", "172.16.0.0/12"]
    #               Loopback.loopback, link-local, Docker
    hostSiteRelations:  # Some commentary
      - .* = Site
    clusterSiteRelations:  # Some commentary
      - .* = Site
    clusterTenantRelations: # Some commentary
     - .* = MyCompany
    vmRoleRelations: # Some commentary
      - .* = My Proxmox VM
    hostRoleRelations: # Some commentary
      - .* = My Proxmox Server
```

### What is the problem?

The journal on my server gives many of the following error types:
`
Feb 26 16:11:54 myVM gunicorn[10069]: Bad Request: /api/dcim/mac-addresses/
Feb 26 16:11:54 myVM gunicorn[10064]: Bad Request: /api/dcim/mac-addresses/
Feb 26 16:11:54 myVM gunicorn[10069]: Bad Request: /api/ipam/ip-addresses/
Feb 26 16:11:54 myVM gunicorn[10068]: Bad Request: /api/dcim/mac-addresses/
`

Furthermore, SSOT fails with a Go stack-trace and Netbox Gunicorn gives many failed errors. I appended two files containing these messages

### Steps to reproduce

I simply run SSOT with the configuration I supplied.

### What did you expect to happen?

I expect the program to run successfully.

The program runs successfully for another Proxmox cluster I have access to, albeit with many MAC-adres related errors.

### What actually happened?

The program exited and I was sad.

The program exits during the process of associating a MACAddress object with a VM interface. There are around 7 attempts of doing this, then it crashes. What all the AssignedObjectIDs have in common is that they are "Loopback Pseudo-Interface" without a MAC-adres in Proxmox. May be related, may be not.

See appended files:
[Gunicorn_Errors.txt](https://github.com/user-attachments/files/18987784/Gunicorn_Errors.txt)
[GoRoutine_Errors.txt](https://github.com/user-attachments/files/18987786/GoRoutine_Errors.txt)

### Share DEBUG-level logs (remove sensitive information)

```plaintext

```

### Share your environment details

` 
Virtualization: kvm
Operating System: Debian GNU/Linux 12 (bookworm)
Kernel: Linux 6.1.0-21-amd64
Architecture: x86-64
Hardware Vendor: QEMU
Hardware Model: Standard PC _i440FX + PIIX, 1996_
Firmware Version: rel-1.16.2-0-gea1b7a073390-prebuilt.qemu.org
`
