### ISSUE TITLE
[Bug] FMC tagged vlans

### ISSUE THREAD

**Issue by Geekul** [SRC-doo/netbox-ssot#528]
### Is this urgent?

No

### How are you running netbox-ssot?

Docker

### Which version of netbox are you using

v1.11.1

### Which version of netbox-ssot are you running

v1.11.1

### Which module has the issue?

FMC

### Share your configuration

```yaml
source:
  - name: fmc
    type: fmc
    hostname: xxxx
    username: xxxx
    password: xxxx
    validateCert: True
    hostTenantRelations:
      - .* = xxxx
    hostSiteRelations:
      - .* = DefaultSite
    vlanTenantRelations:
      - .* = xxxx
```

### What is the problem?

2025/03/21 08:40:37 add_items.go:1110   DEBUG   (fmc): Interface FTD-02/Vlan9 does not exist in Netbox. Creating it...
2025/03/21 08:40:37 rest.go:164         DEBUG   (fmc): Creating objects.Interface with path /api/dcim/interfaces/ with data: Interface{Name: Vlan9, Device: FTD-02, Type: Virtual}
2025/03/21 08:40:37 main.go:117         ERROR   (fmc): sync subinterfaces: add vlan interface: unexpected status code: 400: {"tagged_vlans":["Interface mode does not support tagged vlans"]}
2025/03/21 08:40:37 main.go:136         INFO    (main): Skipping removing orphaned objects because run failed...
2025/03/21 08:40:37 main.go:152         INFO    (main): ⚠ syncing of source fmc failed with: sync subinterfaces: add vlan interface: unexpected status code: 400: {"tagged_vlans":["Interface mode does not support tagged vlans"]}

### Steps to reproduce

docker run

### What did you expect to happen?

n/a

### What actually happened?

n/a

### Share DEBUG-level logs (remove sensitive information)

```plaintext

```
