### ISSUE TITLE
[Bug] Primary IP selection with VMware

### ISSUE THREAD

**Issue by n-rodriguez** [SRC-doo/netbox-ssot#529]
### Is this urgent?

Yes, it's critical

### How are you running netbox-ssot?

From source (Go)

### Which version of netbox are you using

4.2.6

### Which version of netbox-ssot are you running

1.11.4

### Which module has the issue?

VMware

### Share your configuration

```yaml
---
logger:
  level: 3
  dest: ""

netbox:
  apiToken: "foo"
  hostname: "netbox.foo.corp"
  httpScheme: http
  port: 80
  timeout: 30
  sourcePriority: ["vcenter67.corp"]
  removeOrphans: false

source:
  - name: vcenter67.corp
    type: vmware
    hostname: vcenter67.corp
    username: administrator@vsphere.local
    password: "password"
    clusterSiteRelations:
      - .* = Foo
    hostSiteRelations:
      - .* = Foo
    clusterTenantRelations:
      - .* = ACME
    hostTenantRelations:
      - .* = ACME
    vmTenantRelations:
      - .* = ACME
    hostRoleRelations:
      - .* = Hypervisor ESX
    vmRoleRelations:
      - .* = Virtual Machine ESX
    vlanTenantRelations:
      - .* = ACME
    vlanSiteRelations:
      - .* = Foo
```

### What is the problem?

`netbox-ssot` picks the wrong primary ip address

### Steps to reproduce

1. create a vm with 2 ip addresses
2. run `netbox-ssot`
3. the wrong primary ip address is assigned to the virtual machine in netbox

### What did you expect to happen?

The right primary ip address is assigned to the virtual machine in netbox

### What actually happened?

the wrong primary ip address is assigned to the virtual machine in netbox

### Share DEBUG-level logs (remove sensitive information)

```plaintext

```
