### ISSUE TITLE
[Bug] FMC Cluster interfaces

### ISSUE THREAD

**Issue by Geekul** [SRC-doo/netbox-ssot#530]
### Is this urgent?

No

### How are you running netbox-ssot?

Docker

### Which version of netbox are you using

4.2.5

### Which version of netbox-ssot are you running

1.11.4

### Which module has the issue?

General (not module-specific)

### Share your configuration

```yaml
source:

  - name: fmc
    type: fmc
    hostname: fmc.example.com
    username: user
    password: password
    validateCert: True
    hostTenantRelations:
      - .* = DefaultSite
    hostSiteRelations:
      - .* = DefaultSite
    vlanTenantRelations:
      - .* = DefaultSite
```

### What is the problem?

n/a

### Steps to reproduce

n/a

### What did you expect to happen?

n/a

### What actually happened?

n/a

### Share DEBUG-level logs (remove sensitive information)

```plaintext

```

### Share your environment details

![Image](https://github.com/user-attachments/assets/b4f09ec9-bf9f-45e7-8f05-dee218048471)

Hello,
I have 4 devices in 2 sites, configured as in the image above.

The problem is that it only brings the interfaces from the Standby Device from Site1 to my netbox, the other devices are brought in, but without interfaces.

Thank you
